//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianPing.WorkFlow.ServiceProvider.K2Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JsonResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class JsonResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                if ((object.ReferenceEquals(this.msgField, value) != true)) {
                    this.msgField = value;
                    this.RaisePropertyChanged("msg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="K2TaskQueryPara", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class K2TaskQueryPara : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int LoginIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DianPing.WorkFlow.ServiceProvider.K2Service.ArrayOfInt ProcInstIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DianPing.WorkFlow.ServiceProvider.K2Service.ArrayOfString ProcessCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolioField;
        
        private System.DateTime StartDateField;
        
        private System.DateTime EndDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int LoginId {
            get {
                return this.LoginIdField;
            }
            set {
                if ((this.LoginIdField.Equals(value) != true)) {
                    this.LoginIdField = value;
                    this.RaisePropertyChanged("LoginId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public DianPing.WorkFlow.ServiceProvider.K2Service.ArrayOfInt ProcInstId {
            get {
                return this.ProcInstIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcInstIdField, value) != true)) {
                    this.ProcInstIdField = value;
                    this.RaisePropertyChanged("ProcInstId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public DianPing.WorkFlow.ServiceProvider.K2Service.ArrayOfString ProcessCode {
            get {
                return this.ProcessCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessCodeField, value) != true)) {
                    this.ProcessCodeField = value;
                    this.RaisePropertyChanged("ProcessCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Folio {
            get {
                return this.FolioField;
            }
            set {
                if ((object.ReferenceEquals(this.FolioField, value) != true)) {
                    this.FolioField = value;
                    this.RaisePropertyChanged("Folio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="K2Task", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class K2Task : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProcInstIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApproveURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolioField;
        
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProcInstId {
            get {
                return this.ProcInstIdField;
            }
            set {
                if ((this.ProcInstIdField.Equals(value) != true)) {
                    this.ProcInstIdField = value;
                    this.RaisePropertyChanged("ProcInstId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProcessCode {
            get {
                return this.ProcessCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessCodeField, value) != true)) {
                    this.ProcessCodeField = value;
                    this.RaisePropertyChanged("ProcessCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SN {
            get {
                return this.SNField;
            }
            set {
                if ((object.ReferenceEquals(this.SNField, value) != true)) {
                    this.SNField = value;
                    this.RaisePropertyChanged("SN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ApproveURL {
            get {
                return this.ApproveURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ApproveURLField, value) != true)) {
                    this.ApproveURLField = value;
                    this.RaisePropertyChanged("ApproveURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ProcessName {
            get {
                return this.ProcessNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessNameField, value) != true)) {
                    this.ProcessNameField = value;
                    this.RaisePropertyChanged("ProcessName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Folio {
            get {
                return this.FolioField;
            }
            set {
                if ((object.ReferenceEquals(this.FolioField, value) != true)) {
                    this.FolioField = value;
                    this.RaisePropertyChanged("Folio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comment", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Comment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActivityNameField;
        
        private System.DateTime AddDateField;
        
        private int CommentIDField;
        
        private int LoginIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessCodeField;
        
        private int ProcInstIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RealNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Action {
            get {
                return this.ActionField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionField, value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ActionTo {
            get {
                return this.ActionToField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionToField, value) != true)) {
                    this.ActionToField = value;
                    this.RaisePropertyChanged("ActionTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ActivityName {
            get {
                return this.ActivityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivityNameField, value) != true)) {
                    this.ActivityNameField = value;
                    this.RaisePropertyChanged("ActivityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime AddDate {
            get {
                return this.AddDateField;
            }
            set {
                if ((this.AddDateField.Equals(value) != true)) {
                    this.AddDateField = value;
                    this.RaisePropertyChanged("AddDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CommentID {
            get {
                return this.CommentIDField;
            }
            set {
                if ((this.CommentIDField.Equals(value) != true)) {
                    this.CommentIDField = value;
                    this.RaisePropertyChanged("CommentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int LoginID {
            get {
                return this.LoginIDField;
            }
            set {
                if ((this.LoginIDField.Equals(value) != true)) {
                    this.LoginIDField = value;
                    this.RaisePropertyChanged("LoginID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Memo {
            get {
                return this.MemoField;
            }
            set {
                if ((object.ReferenceEquals(this.MemoField, value) != true)) {
                    this.MemoField = value;
                    this.RaisePropertyChanged("Memo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProcessCode {
            get {
                return this.ProcessCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessCodeField, value) != true)) {
                    this.ProcessCodeField = value;
                    this.RaisePropertyChanged("ProcessCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int ProcInstID {
            get {
                return this.ProcInstIDField;
            }
            set {
                if ((this.ProcInstIDField.Equals(value) != true)) {
                    this.ProcInstIDField = value;
                    this.RaisePropertyChanged("ProcInstID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string RealName {
            get {
                return this.RealNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RealNameField, value) != true)) {
                    this.RealNameField = value;
                    this.RaisePropertyChanged("RealName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="K2Status", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class K2Status : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProcInstIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActivityField;
        
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DianPing.WorkFlow.ServiceProvider.K2Service.ArrayOfInt LoginIdsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProcInstId {
            get {
                return this.ProcInstIdField;
            }
            set {
                if ((this.ProcInstIdField.Equals(value) != true)) {
                    this.ProcInstIdField = value;
                    this.RaisePropertyChanged("ProcInstId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Folio {
            get {
                return this.FolioField;
            }
            set {
                if ((object.ReferenceEquals(this.FolioField, value) != true)) {
                    this.FolioField = value;
                    this.RaisePropertyChanged("Folio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Activity {
            get {
                return this.ActivityField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivityField, value) != true)) {
                    this.ActivityField = value;
                    this.RaisePropertyChanged("Activity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public DianPing.WorkFlow.ServiceProvider.K2Service.ArrayOfInt LoginIds {
            get {
                return this.LoginIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginIdsField, value) != true)) {
                    this.LoginIdsField = value;
                    this.RaisePropertyChanged("LoginIds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="K2Service.K2ServiceSoap")]
    public interface K2ServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 processCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StartProcess", ReplyAction="*")]
        DianPing.WorkFlow.ServiceProvider.K2Service.StartProcessResponse StartProcess(DianPing.WorkFlow.ServiceProvider.K2Service.StartProcessRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 processCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ApproveK2Process", ReplyAction="*")]
        DianPing.WorkFlow.ServiceProvider.K2Service.ApproveK2ProcessResponse ApproveK2Process(DianPing.WorkFlow.ServiceProvider.K2Service.ApproveK2ProcessRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 queryPara 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMyTaskList", ReplyAction="*")]
        DianPing.WorkFlow.ServiceProvider.K2Service.GetMyTaskListResponse GetMyTaskList(DianPing.WorkFlow.ServiceProvider.K2Service.GetMyTaskListRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 queryPara 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMyStartedTaskList", ReplyAction="*")]
        DianPing.WorkFlow.ServiceProvider.K2Service.GetMyStartedTaskListResponse GetMyStartedTaskList(DianPing.WorkFlow.ServiceProvider.K2Service.GetMyStartedTaskListRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 procInstId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCommentByList", ReplyAction="*")]
        DianPing.WorkFlow.ServiceProvider.K2Service.GetCommentByListResponse GetCommentByList(DianPing.WorkFlow.ServiceProvider.K2Service.GetCommentByListRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 folio 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProcessStatus", ReplyAction="*")]
        DianPing.WorkFlow.ServiceProvider.K2Service.GetProcessStatusResponse GetProcessStatus(DianPing.WorkFlow.ServiceProvider.K2Service.GetProcessStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartProcessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StartProcess", Namespace="http://tempuri.org/", Order=0)]
        public DianPing.WorkFlow.ServiceProvider.K2Service.StartProcessRequestBody Body;
        
        public StartProcessRequest() {
        }
        
        public StartProcessRequest(DianPing.WorkFlow.ServiceProvider.K2Service.StartProcessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StartProcessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string processCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int loginId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ObjectId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Folio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string jsonData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string apiKey;
        
        public StartProcessRequestBody() {
        }
        
        public StartProcessRequestBody(string processCode, int loginId, string ObjectId, string Folio, string jsonData, string apiKey) {
            this.processCode = processCode;
            this.loginId = loginId;
            this.ObjectId = ObjectId;
            this.Folio = Folio;
            this.jsonData = jsonData;
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartProcessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StartProcessResponse", Namespace="http://tempuri.org/", Order=0)]
        public DianPing.WorkFlow.ServiceProvider.K2Service.StartProcessResponseBody Body;
        
        public StartProcessResponse() {
        }
        
        public StartProcessResponse(DianPing.WorkFlow.ServiceProvider.K2Service.StartProcessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StartProcessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DianPing.WorkFlow.ServiceProvider.K2Service.JsonResult StartProcessResult;
        
        public StartProcessResponseBody() {
        }
        
        public StartProcessResponseBody(DianPing.WorkFlow.ServiceProvider.K2Service.JsonResult StartProcessResult) {
            this.StartProcessResult = StartProcessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApproveK2ProcessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApproveK2Process", Namespace="http://tempuri.org/", Order=0)]
        public DianPing.WorkFlow.ServiceProvider.K2Service.ApproveK2ProcessRequestBody Body;
        
        public ApproveK2ProcessRequest() {
        }
        
        public ApproveK2ProcessRequest(DianPing.WorkFlow.ServiceProvider.K2Service.ApproveK2ProcessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ApproveK2ProcessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string processCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int loginId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string actionString;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string memo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string jsonData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string apiKey;
        
        public ApproveK2ProcessRequestBody() {
        }
        
        public ApproveK2ProcessRequestBody(string processCode, string sn, int loginId, string actionString, string memo, string jsonData, string apiKey) {
            this.processCode = processCode;
            this.sn = sn;
            this.loginId = loginId;
            this.actionString = actionString;
            this.memo = memo;
            this.jsonData = jsonData;
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApproveK2ProcessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApproveK2ProcessResponse", Namespace="http://tempuri.org/", Order=0)]
        public DianPing.WorkFlow.ServiceProvider.K2Service.ApproveK2ProcessResponseBody Body;
        
        public ApproveK2ProcessResponse() {
        }
        
        public ApproveK2ProcessResponse(DianPing.WorkFlow.ServiceProvider.K2Service.ApproveK2ProcessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ApproveK2ProcessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DianPing.WorkFlow.ServiceProvider.K2Service.JsonResult ApproveK2ProcessResult;
        
        public ApproveK2ProcessResponseBody() {
        }
        
        public ApproveK2ProcessResponseBody(DianPing.WorkFlow.ServiceProvider.K2Service.JsonResult ApproveK2ProcessResult) {
            this.ApproveK2ProcessResult = ApproveK2ProcessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMyTaskListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMyTaskList", Namespace="http://tempuri.org/", Order=0)]
        public DianPing.WorkFlow.ServiceProvider.K2Service.GetMyTaskListRequestBody Body;
        
        public GetMyTaskListRequest() {
        }
        
        public GetMyTaskListRequest(DianPing.WorkFlow.ServiceProvider.K2Service.GetMyTaskListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMyTaskListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DianPing.WorkFlow.ServiceProvider.K2Service.K2TaskQueryPara queryPara;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int startNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int limitNum;
        
        public GetMyTaskListRequestBody() {
        }
        
        public GetMyTaskListRequestBody(DianPing.WorkFlow.ServiceProvider.K2Service.K2TaskQueryPara queryPara, string apiKey, int startNum, int limitNum) {
            this.queryPara = queryPara;
            this.apiKey = apiKey;
            this.startNum = startNum;
            this.limitNum = limitNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMyTaskListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMyTaskListResponse", Namespace="http://tempuri.org/", Order=0)]
        public DianPing.WorkFlow.ServiceProvider.K2Service.GetMyTaskListResponseBody Body;
        
        public GetMyTaskListResponse() {
        }
        
        public GetMyTaskListResponse(DianPing.WorkFlow.ServiceProvider.K2Service.GetMyTaskListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMyTaskListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DianPing.WorkFlow.ServiceProvider.K2Service.K2Task[] GetMyTaskListResult;
        
        public GetMyTaskListResponseBody() {
        }
        
        public GetMyTaskListResponseBody(DianPing.WorkFlow.ServiceProvider.K2Service.K2Task[] GetMyTaskListResult) {
            this.GetMyTaskListResult = GetMyTaskListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMyStartedTaskListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMyStartedTaskList", Namespace="http://tempuri.org/", Order=0)]
        public DianPing.WorkFlow.ServiceProvider.K2Service.GetMyStartedTaskListRequestBody Body;
        
        public GetMyStartedTaskListRequest() {
        }
        
        public GetMyStartedTaskListRequest(DianPing.WorkFlow.ServiceProvider.K2Service.GetMyStartedTaskListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMyStartedTaskListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DianPing.WorkFlow.ServiceProvider.K2Service.K2TaskQueryPara queryPara;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int startNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int limitNum;
        
        public GetMyStartedTaskListRequestBody() {
        }
        
        public GetMyStartedTaskListRequestBody(DianPing.WorkFlow.ServiceProvider.K2Service.K2TaskQueryPara queryPara, string apiKey, int startNum, int limitNum) {
            this.queryPara = queryPara;
            this.apiKey = apiKey;
            this.startNum = startNum;
            this.limitNum = limitNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMyStartedTaskListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMyStartedTaskListResponse", Namespace="http://tempuri.org/", Order=0)]
        public DianPing.WorkFlow.ServiceProvider.K2Service.GetMyStartedTaskListResponseBody Body;
        
        public GetMyStartedTaskListResponse() {
        }
        
        public GetMyStartedTaskListResponse(DianPing.WorkFlow.ServiceProvider.K2Service.GetMyStartedTaskListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMyStartedTaskListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DianPing.WorkFlow.ServiceProvider.K2Service.K2Task[] GetMyStartedTaskListResult;
        
        public GetMyStartedTaskListResponseBody() {
        }
        
        public GetMyStartedTaskListResponseBody(DianPing.WorkFlow.ServiceProvider.K2Service.K2Task[] GetMyStartedTaskListResult) {
            this.GetMyStartedTaskListResult = GetMyStartedTaskListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCommentByListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCommentByList", Namespace="http://tempuri.org/", Order=0)]
        public DianPing.WorkFlow.ServiceProvider.K2Service.GetCommentByListRequestBody Body;
        
        public GetCommentByListRequest() {
        }
        
        public GetCommentByListRequest(DianPing.WorkFlow.ServiceProvider.K2Service.GetCommentByListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCommentByListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DianPing.WorkFlow.ServiceProvider.K2Service.ArrayOfInt procInstId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apiKey;
        
        public GetCommentByListRequestBody() {
        }
        
        public GetCommentByListRequestBody(DianPing.WorkFlow.ServiceProvider.K2Service.ArrayOfInt procInstId, string apiKey) {
            this.procInstId = procInstId;
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCommentByListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCommentByListResponse", Namespace="http://tempuri.org/", Order=0)]
        public DianPing.WorkFlow.ServiceProvider.K2Service.GetCommentByListResponseBody Body;
        
        public GetCommentByListResponse() {
        }
        
        public GetCommentByListResponse(DianPing.WorkFlow.ServiceProvider.K2Service.GetCommentByListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCommentByListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DianPing.WorkFlow.ServiceProvider.K2Service.Comment[] GetCommentByListResult;
        
        public GetCommentByListResponseBody() {
        }
        
        public GetCommentByListResponseBody(DianPing.WorkFlow.ServiceProvider.K2Service.Comment[] GetCommentByListResult) {
            this.GetCommentByListResult = GetCommentByListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProcessStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProcessStatus", Namespace="http://tempuri.org/", Order=0)]
        public DianPing.WorkFlow.ServiceProvider.K2Service.GetProcessStatusRequestBody Body;
        
        public GetProcessStatusRequest() {
        }
        
        public GetProcessStatusRequest(DianPing.WorkFlow.ServiceProvider.K2Service.GetProcessStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProcessStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int procInstId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string folio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apiKey;
        
        public GetProcessStatusRequestBody() {
        }
        
        public GetProcessStatusRequestBody(int procInstId, string folio, string apiKey) {
            this.procInstId = procInstId;
            this.folio = folio;
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProcessStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProcessStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public DianPing.WorkFlow.ServiceProvider.K2Service.GetProcessStatusResponseBody Body;
        
        public GetProcessStatusResponse() {
        }
        
        public GetProcessStatusResponse(DianPing.WorkFlow.ServiceProvider.K2Service.GetProcessStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProcessStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DianPing.WorkFlow.ServiceProvider.K2Service.K2Status[] GetProcessStatusResult;
        
        public GetProcessStatusResponseBody() {
        }
        
        public GetProcessStatusResponseBody(DianPing.WorkFlow.ServiceProvider.K2Service.K2Status[] GetProcessStatusResult) {
            this.GetProcessStatusResult = GetProcessStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface K2ServiceSoapChannel : DianPing.WorkFlow.ServiceProvider.K2Service.K2ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class K2ServiceSoapClient : System.ServiceModel.ClientBase<DianPing.WorkFlow.ServiceProvider.K2Service.K2ServiceSoap>, DianPing.WorkFlow.ServiceProvider.K2Service.K2ServiceSoap {
        
        public K2ServiceSoapClient() {
        }
        
        public K2ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public K2ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public K2ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public K2ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DianPing.WorkFlow.ServiceProvider.K2Service.StartProcessResponse DianPing.WorkFlow.ServiceProvider.K2Service.K2ServiceSoap.StartProcess(DianPing.WorkFlow.ServiceProvider.K2Service.StartProcessRequest request) {
            return base.Channel.StartProcess(request);
        }
        
        public DianPing.WorkFlow.ServiceProvider.K2Service.JsonResult StartProcess(string processCode, int loginId, string ObjectId, string Folio, string jsonData, string apiKey) {
            DianPing.WorkFlow.ServiceProvider.K2Service.StartProcessRequest inValue = new DianPing.WorkFlow.ServiceProvider.K2Service.StartProcessRequest();
            inValue.Body = new DianPing.WorkFlow.ServiceProvider.K2Service.StartProcessRequestBody();
            inValue.Body.processCode = processCode;
            inValue.Body.loginId = loginId;
            inValue.Body.ObjectId = ObjectId;
            inValue.Body.Folio = Folio;
            inValue.Body.jsonData = jsonData;
            inValue.Body.apiKey = apiKey;
            DianPing.WorkFlow.ServiceProvider.K2Service.StartProcessResponse retVal = ((DianPing.WorkFlow.ServiceProvider.K2Service.K2ServiceSoap)(this)).StartProcess(inValue);
            return retVal.Body.StartProcessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DianPing.WorkFlow.ServiceProvider.K2Service.ApproveK2ProcessResponse DianPing.WorkFlow.ServiceProvider.K2Service.K2ServiceSoap.ApproveK2Process(DianPing.WorkFlow.ServiceProvider.K2Service.ApproveK2ProcessRequest request) {
            return base.Channel.ApproveK2Process(request);
        }
        
        public DianPing.WorkFlow.ServiceProvider.K2Service.JsonResult ApproveK2Process(string processCode, string sn, int loginId, string actionString, string memo, string jsonData, string apiKey) {
            DianPing.WorkFlow.ServiceProvider.K2Service.ApproveK2ProcessRequest inValue = new DianPing.WorkFlow.ServiceProvider.K2Service.ApproveK2ProcessRequest();
            inValue.Body = new DianPing.WorkFlow.ServiceProvider.K2Service.ApproveK2ProcessRequestBody();
            inValue.Body.processCode = processCode;
            inValue.Body.sn = sn;
            inValue.Body.loginId = loginId;
            inValue.Body.actionString = actionString;
            inValue.Body.memo = memo;
            inValue.Body.jsonData = jsonData;
            inValue.Body.apiKey = apiKey;
            DianPing.WorkFlow.ServiceProvider.K2Service.ApproveK2ProcessResponse retVal = ((DianPing.WorkFlow.ServiceProvider.K2Service.K2ServiceSoap)(this)).ApproveK2Process(inValue);
            return retVal.Body.ApproveK2ProcessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DianPing.WorkFlow.ServiceProvider.K2Service.GetMyTaskListResponse DianPing.WorkFlow.ServiceProvider.K2Service.K2ServiceSoap.GetMyTaskList(DianPing.WorkFlow.ServiceProvider.K2Service.GetMyTaskListRequest request) {
            return base.Channel.GetMyTaskList(request);
        }
        
        public DianPing.WorkFlow.ServiceProvider.K2Service.K2Task[] GetMyTaskList(DianPing.WorkFlow.ServiceProvider.K2Service.K2TaskQueryPara queryPara, string apiKey, int startNum, int limitNum) {
            DianPing.WorkFlow.ServiceProvider.K2Service.GetMyTaskListRequest inValue = new DianPing.WorkFlow.ServiceProvider.K2Service.GetMyTaskListRequest();
            inValue.Body = new DianPing.WorkFlow.ServiceProvider.K2Service.GetMyTaskListRequestBody();
            inValue.Body.queryPara = queryPara;
            inValue.Body.apiKey = apiKey;
            inValue.Body.startNum = startNum;
            inValue.Body.limitNum = limitNum;
            DianPing.WorkFlow.ServiceProvider.K2Service.GetMyTaskListResponse retVal = ((DianPing.WorkFlow.ServiceProvider.K2Service.K2ServiceSoap)(this)).GetMyTaskList(inValue);
            return retVal.Body.GetMyTaskListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DianPing.WorkFlow.ServiceProvider.K2Service.GetMyStartedTaskListResponse DianPing.WorkFlow.ServiceProvider.K2Service.K2ServiceSoap.GetMyStartedTaskList(DianPing.WorkFlow.ServiceProvider.K2Service.GetMyStartedTaskListRequest request) {
            return base.Channel.GetMyStartedTaskList(request);
        }
        
        public DianPing.WorkFlow.ServiceProvider.K2Service.K2Task[] GetMyStartedTaskList(DianPing.WorkFlow.ServiceProvider.K2Service.K2TaskQueryPara queryPara, string apiKey, int startNum, int limitNum) {
            DianPing.WorkFlow.ServiceProvider.K2Service.GetMyStartedTaskListRequest inValue = new DianPing.WorkFlow.ServiceProvider.K2Service.GetMyStartedTaskListRequest();
            inValue.Body = new DianPing.WorkFlow.ServiceProvider.K2Service.GetMyStartedTaskListRequestBody();
            inValue.Body.queryPara = queryPara;
            inValue.Body.apiKey = apiKey;
            inValue.Body.startNum = startNum;
            inValue.Body.limitNum = limitNum;
            DianPing.WorkFlow.ServiceProvider.K2Service.GetMyStartedTaskListResponse retVal = ((DianPing.WorkFlow.ServiceProvider.K2Service.K2ServiceSoap)(this)).GetMyStartedTaskList(inValue);
            return retVal.Body.GetMyStartedTaskListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DianPing.WorkFlow.ServiceProvider.K2Service.GetCommentByListResponse DianPing.WorkFlow.ServiceProvider.K2Service.K2ServiceSoap.GetCommentByList(DianPing.WorkFlow.ServiceProvider.K2Service.GetCommentByListRequest request) {
            return base.Channel.GetCommentByList(request);
        }
        
        public DianPing.WorkFlow.ServiceProvider.K2Service.Comment[] GetCommentByList(DianPing.WorkFlow.ServiceProvider.K2Service.ArrayOfInt procInstId, string apiKey) {
            DianPing.WorkFlow.ServiceProvider.K2Service.GetCommentByListRequest inValue = new DianPing.WorkFlow.ServiceProvider.K2Service.GetCommentByListRequest();
            inValue.Body = new DianPing.WorkFlow.ServiceProvider.K2Service.GetCommentByListRequestBody();
            inValue.Body.procInstId = procInstId;
            inValue.Body.apiKey = apiKey;
            DianPing.WorkFlow.ServiceProvider.K2Service.GetCommentByListResponse retVal = ((DianPing.WorkFlow.ServiceProvider.K2Service.K2ServiceSoap)(this)).GetCommentByList(inValue);
            return retVal.Body.GetCommentByListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DianPing.WorkFlow.ServiceProvider.K2Service.GetProcessStatusResponse DianPing.WorkFlow.ServiceProvider.K2Service.K2ServiceSoap.GetProcessStatus(DianPing.WorkFlow.ServiceProvider.K2Service.GetProcessStatusRequest request) {
            return base.Channel.GetProcessStatus(request);
        }
        
        public DianPing.WorkFlow.ServiceProvider.K2Service.K2Status[] GetProcessStatus(int procInstId, string folio, string apiKey) {
            DianPing.WorkFlow.ServiceProvider.K2Service.GetProcessStatusRequest inValue = new DianPing.WorkFlow.ServiceProvider.K2Service.GetProcessStatusRequest();
            inValue.Body = new DianPing.WorkFlow.ServiceProvider.K2Service.GetProcessStatusRequestBody();
            inValue.Body.procInstId = procInstId;
            inValue.Body.folio = folio;
            inValue.Body.apiKey = apiKey;
            DianPing.WorkFlow.ServiceProvider.K2Service.GetProcessStatusResponse retVal = ((DianPing.WorkFlow.ServiceProvider.K2Service.K2ServiceSoap)(this)).GetProcessStatus(inValue);
            return retVal.Body.GetProcessStatusResult;
        }
    }
}
