//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianPing.WorkFlow.ServiceProvider.EmployeeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRMRoleType", Namespace="http://schemas.datacontract.org/2004/07/API.HR.WCF")]
    public enum CRMRoleType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        销售一级主管 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AE = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        风控品控 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        地区经理 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        销售VP = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        团购财务 = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        合同审核员 = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        项目组 = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        大区经理 = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        保补审核员 = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        保补一级主管 = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        保补二级主管 = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        电商销售 = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        普通销售 = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        小组长 = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        区域主管 = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        城市经理 = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        推广财务 = 18,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeDto", Namespace="http://schemas.datacontract.org/2004/07/DianPing.HR.Application.Dto")]
    [System.SerializableAttribute()]
    public partial class EmployeeDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeIdField, value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginId {
            get {
                return this.LoginIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginIdField, value) != true)) {
                    this.LoginIdField = value;
                    this.RaisePropertyChanged("LoginId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JsonResult", Namespace="http://schemas.datacontract.org/2004/07/DianPing.HR.Application.Dto")]
    [System.SerializableAttribute()]
    public partial class JsonResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int code {
            get {
                return this.codeField;
            }
            set {
                if ((this.codeField.Equals(value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                if ((object.ReferenceEquals(this.msgField, value) != true)) {
                    this.msgField = value;
                    this.RaisePropertyChanged("msg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeService.IHRService")]
    public interface IHRService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHRService/GetUsersBySalesCRMRoleType", ReplyAction="http://tempuri.org/IHRService/GetUsersBySalesCRMRoleTypeResponse")]
        DianPing.WorkFlow.ServiceProvider.EmployeeService.EmployeeDto[] GetUsersBySalesCRMRoleType(DianPing.WorkFlow.ServiceProvider.EmployeeService.CRMRoleType roleType, string loginId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHRService/CreateGmail", ReplyAction="http://tempuri.org/IHRService/CreateGmailResponse")]
        DianPing.WorkFlow.ServiceProvider.EmployeeService.JsonResult CreateGmail(string email, string mobileNo, string realName, string apiKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHRServiceChannel : DianPing.WorkFlow.ServiceProvider.EmployeeService.IHRService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HRServiceClient : System.ServiceModel.ClientBase<DianPing.WorkFlow.ServiceProvider.EmployeeService.IHRService>, DianPing.WorkFlow.ServiceProvider.EmployeeService.IHRService {
        
        public HRServiceClient() {
        }
        
        public HRServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HRServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HRServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HRServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DianPing.WorkFlow.ServiceProvider.EmployeeService.EmployeeDto[] GetUsersBySalesCRMRoleType(DianPing.WorkFlow.ServiceProvider.EmployeeService.CRMRoleType roleType, string loginId) {
            return base.Channel.GetUsersBySalesCRMRoleType(roleType, loginId);
        }
        
        public DianPing.WorkFlow.ServiceProvider.EmployeeService.JsonResult CreateGmail(string email, string mobileNo, string realName, string apiKey) {
            return base.Channel.CreateGmail(email, mobileNo, realName, apiKey);
        }
    }
}
